Yanolza-Miniproject/frontend

src/App.tsx, src/components/Common/Footer.tsx, src/components/Common/Header.tsx, src/components/Common/Layout.tsx, src/index.css, src/main.tsx, src/pages/Main/index.tsx
close #1 
작업하시면서 레이아웃 함께 고려하실 수 있도록 우선 Header, Footer, Outlet 기본 구조만 잡아놓았습니다.
=> Feat: 메인페이지 기본 레이아웃 업데이트

src/components/Cart/CartZero/CartZero.styles.ts, src/components/Cart/CartZero/index.tsx, src/components/Cart/Estimate/Estimate.utils.ts, src/components/Cart/Estimate/index.tsx, src/components/Common/Button.tsx, src/pages/Cart/Cart.styles.ts, src/pages/Cart/index.tsx, src/store/purchaseAtom.ts
close #10 
- 승인 완료되면 아무나 바로 머지 하셔도 되고, 머지 하시면 브랜치도 같이 삭제해주셔도 됩니다!!
예시
```
{
"totalPrice": 330000,
"data": [
{
"room_basket_id": 1,
"accommdation_name": "라마다 제주시티 호텔",
"room_image_url": [
""
],
"room_name": "스위트 더블",
"price": 210000,
"number_guests": 2,
"check_in_at": "2023.11.21",
"check_out_at": "2023.11.24"
},
{
"room_basket_id": 3,
"accommdation_name": "제주 홍스랜드펜션",
"room_image_url": [
""
],
"room_name": "402동",
"price": 120000,
"number_guests": 2,
"check_in_at": "2023.11.21",
"check_out_at": "2023.11.24"
}
]
}
```
```javascript
<Button
text="구매하기" // 버튼 text *필수
type="orange" // default, blue, orange 3가지 구성 - 현재 디자인 반영 *필수
size="lg" // sm, md, lg 3가지 구성 - 이후 필요 시 수정 가능 *필수
style={{ width: "100%" }} // 필요한 스타일 추가 지정 *옵션
onClick={() => {
// 클릭 로직
}} // * 필수
/>
```
=> Feat: 버튼 액션 추가, 빈 카트 화면 컴포넌트 추가, 리코일 총 가격 저장

src/App.tsx, src/api/Category/index.tsx, src/components/Category/CategoryBanner/CategoryBanner.styles.ts, src/components/Category/CategoryBanner/index.tsx, src/components/Category/CategoryFilter/CategoryFilter.constants.ts, src/components/Category/CategoryItemWrapper/index.tsx, src/components/Category/CategoryQuery/index.tsx, src/components/Category/InfiniteScroller/InfiniteScroller.styles.ts, src/components/Category/InfiniteScroller/index.tsx, src/components/SearchListBanner/SearchList.styles.ts, src/components/SearchListBanner/index.tsx, src/hooks/useCategoryInfiniteQuery.ts, src/hooks/useGetValidParams.ts, src/mocks/browser/handlers.ts, src/pages/Category/Category.styles.ts, src/pages/Category/Category.types.ts, src/pages/Category/index.tsx, src/pages/SearchList/SearchList.styles.ts, src/pages/SearchList/index.tsx, src/store/resultsSearchQueryAtom.ts, src/utils/filterDecoder.ts, src/utils/filterTextDecoder.ts
close #23 
- 검색 시 키워드 상단 노출
- 버튼 Hover spring 효과
- 백엔드 api와 맞게 api 수정 및 오류 수정
=> Feat : 검색 완료 창 구현 및 API 수정 pr

src/components/Category/HeartClick/index.test.tsx, src/components/Category/HeartClick/index.tsx
close #40 
jest 실험하면서 배운 내용들입니다!! 혹시라도 검색할 시간을 아낄 수 있을까 싶어서 **배운 내용들을 공유**합니다!!
[민섭 troubleShooting](https://github.com/Yanolza-Miniproject/frontend/wiki/%EB%AF%BC%EC%84%AD-trouble%E2%80%90shooting%E2%80%902)
heartClick 컴포넌트 test 작성한 예시 올립니다!!
참고로 userEvent 테스팅 라이브러리 설치했습니다!!
**npm install 꼭 부탁드립니다**
=> Feat : jest + react-testing-library 개발 경험 공유 및 예시 코드 작성

jest.config.cjs, package-lock.json, package.json, src/components/Cart/CartList/CartList.styles.ts, src/components/Cart/CartList/CartList.test.tsx, src/components/Cart/CartList/CartList.types.ts, src/components/Cart/CartList/CartLust.utils.ts, src/components/Cart/CartList/index.tsx, src/pages/Cart/index.tsx
#43
- 테스트하는 컴포넌트에 import 해오는 부분에 SVG를 import 하면 jest가 인식을 못 하는 거 같습니다. 일단 jest 설정 약간 변경하여 작동하도록 하였는데 이게 저만 그런 거일 수도 있어서 확인 한번 해주시면 감사드리겠습니다!!
- "jest-svg-transformer" 설치하였습니다!
=> Fix: jest SVG import하는 파일 안되는 문제

src/components/Cart/CartItem/CartItems.utils.ts, src/components/Cart/CartItem/index.tsx, src/components/Cart/CartList/CartList.test.tsx, src/components/Cart/CartList/CartList.types.ts, src/components/Cart/CartList/CartList.utils.ts, src/components/Cart/CartList/index.tsx, src/pages/Cart/Cart.test.tsx, src/pages/Cart/index.tsx
=> Feat: 장바구니 페이지 로딩, 데이터 아이템 렌더링 테스트 추가

src/components/DetailList/RoomList/index.tsx
=> Fix : atom Name 수정

package.json
=> Fix : 라우팅 설정 변경 (error페이지 라우팅)

.gitignore, src/hooks/useAxios.ts, src/hooks/useCartFetch.ts
#62 
close(X)
브랜치삭제(X)
- 인증 필요 요청에 토큰은 현재 임의의 문자열인데 이후 진짜 토큰을 가져오는 방식으로 바꾸면 될 거 같습니다.
- 에러 핸들링 부분도 콘솔에 출력되도록만 하였는데 한번 회의한 후 공통적인 에러처리를 결정하고 함수 에러 핸들링 함수 내부에 작성하면 될 거 같습니다.
- baseURL은 환경변수로 저장해 놓았습니다. 현재 baseURL은 /api/v1이고 이후 수정 예정
- 사용
```javascript
// 인증이 필요한 경우
import { authInstance } from "./useAxios";
authInstance.get("/baskets"); // authInstance.get("/api/vi/baskets"); (X)
// 인증이 필요 없는 경우
import { baseInstance } from "./useAxios";
baseInstance.get("/baskets"); // authInstance.get("/api/vi/baskets"); (X)
```
- !!!!!머지 시 꼭 루트경로에 .env파일 생성 후 VITE_APP_API_BASE_URL = /api/v1 이거 넣어주세요!!!!!
=> Feat: 공통 axios 인스턴스 생성

src/hooks/useGeolocation.ts, src/pages/Cart/index.tsx
#62 
모르고 해당 이슈에서 작업해버렸습니다 ㅠㅠ
- 해당 훅 사용 시 위치 브라우저에서 위치 정보 동의 창이 뜨고 허용하면 위치 정보가 저장 될 겁니다.
- 사용
```javascript
import useGeolocation from "../../hooks/useGeolocation";
const locaition = useGeolocation();
console.log(locaition);
```
```javascript
{
"isLoading": true, // 로딩 상태
"coordinate": {
"lat": 36.2807296,
"lng": 127.2479744
}, // 현재 위치 좌표값
"cityCode": 3 // 현재 위치에 대한 검색 코드 (저는 충청도라 충청도 검색코드인 3이 저장됩니다)
}
```
- 머지 되면 다들 현재 자신의 위치로 잘 뜨는지 확인 한번 부탁드립니다!!!
=> Feat: 사용자 위치 정보 받아오기

src/pages/Cart/index.tsx, vite.config.ts
- 타켓 주소만 변경하였습니다. 환경 변수로 적용하려 했는데 잘 안되서 일단 다같이 공통적으로 작업하기 위해 pr 올립니다!
- axios요청을 그냥 보낼 때는 baseURL까지 작성 해주셔야 되고 useAxios를 사용하면 baseURL 제외 하고 작성 가능합니다.
따라서 axios 요청 있는 부분을 useAxios에서 인스턴스 불러와서 하는것을 권장 드립니다.
- 환경변수가 변경 되었습니다 VITE_APP_API_BASE_URL=/api 이런식으로 고쳐주세요!!
=> Fix: 프록시 타겟 주소 변경

src/components/Common/Header.tsx, src/hooks/useAxios.ts, src/pages/Cart/index.tsx
- 임시로 인증이 필요한 요청이 가능하도록 변경하였습니다.
- 헤더에 로그인 버튼 누르면 db에 들어가 있는 유저로 로그인 되고 토큰이 로컬스토리지에 저장 됩니다(임시)
- 인증 필요 요청 시 authInstance를 사용하면 자동으로 헤더에 토큰이 담겨서 서버로 요청이 갑니다.
- 현재 테스트 결과는 잘 나오고 혹시 이상한 점 있으면 바로 알려주세요!!
- 토큰 만료시간이 지금은 5분이라 5분마다 로그인 버튼 눌러줘야 합니다 ㅠㅠ 
- 이후에 인증 오류에 대해서는 공통 에러핸들링을 추가 할 예정 입니다!
*************꼭 .env 파일 VITE_APP_API_BASE_URL=/api <- 이거로 바꿔주세요!****************
=> Feat: 인증 필요 요청 추가 (임시)

vite.config.ts
=> Feat : target test2

src/api/Category/index.tsx, src/components/Common/Header.tsx, src/pages/Signup/index.tsx, vite.config.ts
=> Test : api 요청 가능한 지 test

src/api/Category/index.tsx, src/pages/Signup/index.tsx
=> Feat : test 주소 변경 후 test

src/pages/Signin/index.tsx, vite.config.ts
=> Feat : 도메인 주소 변경 후 test

src/api/Category/index.tsx, src/main.tsx, src/mocks/browser/handlers.ts, src/pages/Signin/index.tsx, src/pages/Signup/index.tsx, vite.config.ts
=> Feat : https 통신 test

src/api/Category/index.tsx, src/pages/Signup/index.tsx
=> Feat : http 프록시 제거 test

src/pages/Signin/index.tsx, src/pages/Signup/index.tsx
=> Feat : test 변경 커밋

vercel.json
=> Fix: vercel 포록시 주소 변경

src/components/Cart/CartItem/index.tsx, src/components/Cart/CartList/index.tsx, src/components/Cart/Estimate/index.tsx, src/components/Common/Header.tsx, src/types/index.ts
=> Fix: 장바구니 api 키값 변경

src/components/Main/AccommodationList/index.tsx
#85 
번거롭게 해드려 죄송합니다. 제가 로직을 잘못 이해하고 업데이트를 누락한 부분이 있어 확인 후 수정하였습니다! (링크 수정)
=> Fix: 메인페이지 링크 수정

src/components/Cart/CartItem/CartItems.utils.ts, src/components/Complete/PaymentItems/index.tsx
=> Fix: 오타 수정

src/components/Cart/CartItem/index.tsx, src/components/Cart/CartList/index.tsx, src/components/Cart/Estimate/index.tsx, src/components/Complete/CompleteMessage/CompleteMessage.utils.ts, src/hooks/useCartFetch.ts, src/pages/Cart/index.tsx, src/pages/Complete/index.tsx
- 결제 완료 페이지의 데이터를 일부 바꾼 후 정상적으로 화면이 보이도록 수정하였습니다.
=> Fix: 결제 완료 페이지 데이터 수

src/components/DetailList/ProductTitle/ProductTitle.types.ts, src/components/DetailList/ProductTitle/index.tsx, src/components/DetailList/RoomList/index.tsx, src/pages/DetailList/index.tsx
#84 (clsee (x))
* /detail?accommodation-id=1 에서만 확인 가능합니다.
* 현재 예약 관련 데이터가 없어 날짜별 조회 불가능합니다. 
* detailList 페이지에 숙소 타입 변환 추가했습니다.
=> Feat: detailList 페이지의 RoomList 연동

src/components/Detail/StockStatusBaner/StockStatusBanner.styles.ts, src/components/Detail/StockStatusBaner/index.tsx, src/pages/Detail/Detail.types.ts, src/pages/Detail/index.tsx
#84 
객실 페이지 품절, 품절 임박 배너 연동하였습니다. 재고 5개 이하, 품절 임박 배너 노출입니다.
=> Feat: 객실 페이지 품절, 품절 임박 배너 연동

src/components/SearchListBanner/SearchList.styles.ts, src/components/SearchListBanner/index.tsx, src/pages/SearchList/SearchList.styles.ts, src/pages/SearchList/index.tsx
=> Feat : Results 페이지 외부 디자인 변경

src/pages/Main/index.tsx, src/pages/MyPage/index.tsx
#137 
- 메인페이지내  CheckIn, Checkout date 삭제 로직 추가
- myPage 라우팅 관련 수정
=> Feat: CheckIn, Checkout date 삭제 로직 추가, myPage 라우팅 관련 수정

src/components/Detail/Calendar/Calendar.styles.ts, src/components/Detail/PriceDisplay/PriceDisplay.styles.ts, src/components/Detail/ProductDetails/ProductDetail.styles.ts, src/components/Detail/QuantitySelector/QuantitySelector.styles.ts, src/components/DetailList/ProductInfo/ProductInfo.styles.ts, src/components/DetailList/ProductTitle/ProductTitle.styles.ts, src/components/MyPage/MyOrder/MyOrderItem/MyOrder.styles.ts
=> Design: 이미지 크기 수정, 글자 간격 수정

src/components/Category/CategoryFilter/CategoryFilter.constants.ts, src/components/DetailList/ProductTitle/index.tsx
=> Fix: 숙소 타입명 통일

src/components/Detail/Calendar/index.tsx, src/components/DetailList/Card/Card.styles.ts, src/components/DetailList/ProductImage/ProductImage.styles.ts
#160 
페이지 두개의 캘린더 날짜 선택 동기화했습니다.
=> Fix: 캘린더 날짜 선택 관련 수정

src/components/Signin/InputText/InputText.styles.ts
=> Design: 로그인 로그아웃 노티문구 글씨크기 수정

README.md, src/components/Detail/ActionButtonGroup/index.tsx, src/components/Detail/Calendar/index.tsx, src/components/Detail/PriceDisplay/index.tsx, src/components/Detail/ProductGallery/index.tsx, src/components/Detail/ProductImage/ProductImage.styles.ts, src/components/Detail/ProductImage/ProductImage.types.ts, src/components/Detail/ProductImage/index.tsx, src/components/Detail/QuantitySelector/index.tsx, src/components/Detail/StockStatusBaner/index.tsx, src/components/DetailList/RoomItem/index.tsx, src/components/DetailList/RoomList/RoomList.utils.ts, src/components/DetailList/RoomList/index.tsx
#184 
* 코드리뷰 바탕으로 작성한 코드 리팩토링 (숙소상세/객실상세페이지)
* 리드미 개인 역량 회고 추가
=>  Refactoring: 코드리뷰 바탕으로 작성한 코드 리팩토링 (숙소상세/객실상세페이지)

README.md, index.html, package-lock.json, package.json, src/App.tsx, src/components/Common/Common.styles.ts, src/components/Common/Header.tsx, src/components/Common/Sidebar.test.tsx, src/components/Common/Sidebar.tsx, src/components/Main/AccommodationList/index.tsx, src/components/Search/SearchSelector/SearchOptions/index.test.tsx, src/hooks/useMainListFetch.ts, src/hooks/useSearchHandler.ts, src/pages/NotFound/NotFound.styles.ts, src/pages/NotFound/index.tsx, src/store/searchSelectorAtom.ts
#179 
``seamless-scroll-polyfill 라이브러리 설치하였습니다.``
=> Refactoring: 코드리뷰 바탕으로 작성한 코드 리팩토링 (메인/검색페이지)
